# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout
      
      - run:
          name: see what we have
          command: |
              ls
              ls ~/repo
              ls ~/repo/src
              
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum ".circleci/requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            sudo pip install -r .circleci/requirements.txt

      - save_cache:
          paths:
          key: v1-dependencies-{{ checksum ".circleci/requirements.txt" }}
          
      - run:
          name: Run linter
          working_directory: ~/repo/src
          command: |
              mkdir -p test-reports/flake8
              flake8 . --output-file=test-reports/flake8/flake8.txt

      - run:
          name: run tests
          command: |
            pytest tests/

      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = kjmerf" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc

      - run:
          name: create packages
          command: |
            python setup.py sdist
            python setup.py bdist_wheel
            
      - run:
         name: say something if master
         command: |
             if [ "${CIRCLE_BRANCH}" == "master" ]; then
               echo "I sure hope this is the master branch!"
               pwd
             fi
          
      #- run:
      #    name: upload to pypi
      #    command: |
      #      . venv/bin/activate
      #      twine upload dist/*
