# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum ".circleci/requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r .circleci/requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum ".circleci/requirements.txt" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest tests/

      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = kjmerf" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc

      - run:
          name: create packages
          command: |
            python setup.py sdist
            python setup.py bdist_wheel
      
      - run
          name: show me the files!
          command: |
              echo pwd
              ls > test.txt
              cat test.txt
              
      - run:
         name: say something if master
         command: |
             if [ "${CIRCLE_BRANCH}" == "master" ]; then
               echo "I sure hope this is the master branch!" 
             fi
          
      #- run:
      #    name: upload to pypi
      #    command: |
      #      . venv/bin/activate
      #      twine upload dist/*
